### ISSUE TITLE
处理某些书时产生IndexOutOfRangeException错误

### ISSUE THREAD

**Issue by jywhy6** [Aeroblast/UnpackKindleS#19]
使用[UnpackKindleS](https://github.com/Aeroblast/UnpackKindleS)对已解密的azw3和res进行处理整合，生成epub，我的某些书会产生如下的报错：
```
UnpackKindleS Ver.20220126
https://github.com/Aeroblast/UnpackKindleS
==============START===============
 unknown id 547:4F6E4469736B
 unknown id 548:4F6E4469736B
 unknown id 405:00
 unknown id 407:0000000000000000
 unknown id 403:00
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at UnpackKindleS.Util.SubArray(Byte[] src, UInt64 start, UInt64 length)
   at UnpackKindleS.Azw3File.ProcessRes()
   at UnpackKindleS.Azw3File..ctor(String path)
   at UnpackKindleS.Program.ProcPath(String[] args)
   at UnpackKindleS.Program.Main(String[] args)
```
如果需要文件样本，请留一下邮箱，我发给你。

**Comment by Aeroblast** [comment]
最近开发环境受限，解决可能需要等很久…

**Comment by jywhy6** [comment]
今天简单了解了一下azw3文件的格式，发现我手上导致出错的解密的azw3文件，本身是不完整的（使用KindleUnpack能生成epub，但是最后一张图片明显是损坏的），可能是DeDRM插件处理的问题。
