### ISSUE TITLE
把res文件拖到_Tool_Drop_Dump_azwres.bat报错

### ISSUE THREAD

**Issue by aaqq0pp** [Aeroblast/UnpackKindleS#26]
把res文件拖到_Tool_Drop_Dump_azwres.bat报错如下：
https://github.com/Aeroblast/UnpackKindleS
Dump azw.res
azw6 source:D:\portable softwares\UnpackKindleS_\a.res
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at UnpackKindleS.Util.SubArray(Byte[] src, UInt64 start, UInt64 length)
   at UnpackKindleS.Util.GetUInt32(Byte[] src, UInt64 start)
   at UnpackKindleS.AzwFile.GetSectionInfo()
   at UnpackKindleS.AzwFile..ctor(String path)
   at UnpackKindleS.Azw6File..ctor(String path)
   at UnpackKindleS.Program.DumpHDImage(String[] args)
   at UnpackKindleS.Program.Main(String[] args)

**Comment by aaqq0pp** [comment]
原书是kfx加密的，目前只有epubor可解。我也试了用epubor解密后转换成azw3再和res文件一起拖到_Tool_Drop_Single.bat上，也显示相似报错。
