### ISSUE TITLE
Can't run AZW3_PC_DeDRM.py if system use UTF-8 as encoding

### ISSUE THREAD

**Issue by myuki** [Aeroblast/UnpackKindleS#3]
I use UTF-8 as system encoding. It's a beta feature in Windows 10.

In this setting, UTF-8 is the default encoding in Powershell and CMD.

Log:
```
Traceback (most recent call last):
  File "AZW3_PC_DeDRM.py", line 6, in <module>
  File "e:\apptemp\pip-install-9qp7ma\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 391, in load_module
  File "mobidedrm.py", line 83, in <module>
LookupError: unknown encoding: cp65001
[14524] Failed to execute script AZW3_PC_DeDRM
```

If manually change shell encoding before run bat. It can be solved and run well.
```
chcp 1252
```

**Comment by myuki** [comment]
It seems like a python problem and be fixed in python3.3

See also:
<https://bugs.python.org/issue13216>
<https://docs.python.org/3/whatsnew/3.3.html>

**Comment by Aeroblast** [comment]
原始脚本都是py2的，所以我是没能力/精力去升级py3修复的……
如果可以通过chcp解决，那么可以编辑dedrm.bat，加一句chcp试试。
